### ISSUE TITLE
Publishing data

### ISSUE THREAD

**Issue by Shadow-Genesis** [cole8888/SRNE-Solar-Charge-Controller-Monitor#6]
I'm using the Python version, I was getting a bunch of errors and code crashing from the mqtt. I read your description of the project and saw that it send the data off to another device. I don't have it setup with a second device., so maybe an error due to me not having it setup that way.

`Traceback (most recent call last):
  File "/home/USER/SolarComms/SRNE.py", line 82, in <module>
    client = connect_mqtt()
  File "/home/USER/SolarComms/SRNE.py", line 73, in connect_mqtt
    client.connect(broker, port)
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`

Also, thank you! I was about to pull my hair out trying to get it to work.

**Comment by cole8888** [comment]
I should probably clarify that the multiple devices is for the arduino version only. Since the python version version should already be connected to a network it doesn't need a second device to do that like the arduino version does.

It looks like you do not have a mqtt server setup. If you don't need the mqtt stuff and just want to see everything printed to the terminal you can comment out the mqtt stuff. If you want to use mqtt you will need to setup a mqtt server on your network. You should be able to get one running on the same machine you are running the python code from, here is an article which should help https://pimylifeup.com/raspberry-pi-mosquitto-mqtt-server/

After you get that working then just assign the `broker` variable in the script to be the ip address of the mqtt server you setup.
